version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user
      - product

  user:
    build: ./services/user
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - postgres

  product:
    build: ./services/product
    ports:
      - "3002:3000"
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:

